### ISSUE TITLE
Not listed in Package Control

### ISSUE THREAD

**Issue by michaelnakamura** [NicholasBuse/sublime_DeleteBlankLines#11]
DeleteBlankLines is not listed for install anymore.
It appears as MISSING in the package browser page: https://packagecontrol.io/packages/DeleteBlankLines

**Comment by NicholasBuse** [comment]
I'm not sure what is going on there, no changes on this side.

- My respository is still listed in PC's channel.json: https://github.com/wbond/package_control_channel/blob/master/channel.json#L83
- My packages are still in place: https://github.com/NicholasBuse/sublime_packages/blob/master/packages.json
- The package is still there: https://github.com/NicholasBuse/sublime_DeleteBlankLines/releases/tag/v1.0.7

Maybe there was an GitHub outage at the time of last refresh?

@wbond, do you have any insight on why this (and all three of my packages) are listed as "Missing"?

**Comment by wbond** [comment]
GitHub turned off all TLS versions but 1.2 last night, and the Python 3.3 _ssl module doesn't send the right handshake for that situation. I have been working on a fix today.

**Comment by michaelnakamura** [comment]
Fixed, thanks!
