### ISSUE TITLE
Is OS really matter ?

### ISSUE THREAD

**Issue by bizoo** [NicholasBuse/sublime_DeleteBlankLines#2]
To get the actual line endings of a view you must use view.line_endings()

But doesn't the buffer of ST2 always has a line ending of \n whatever the specified line endings ?
Line endings is only used when writing the physical file.

I'm pretty sure you can remove all OS check and only keep the \n processing, but I didn't test.

**Comment by NicholasBuse** [comment]
Fixed by https://github.com/NicholasBuse/sublime_DeleteBlankLines/commit/9ae04a6f235c4c0fa6874dcb583de3546226bd76
