### ISSUE TITLE
does nothing on osx 10.8.5 & sublime text 3

### ISSUE THREAD

**Issue by bedge** [NicholasBuse/sublime_DeleteBlankLines#5]
No approximate combination of the defined keys works.
fn-ctrl-option-delete
ctrl-option-delete
cmd-option-delete

Any other suggestions?

It also doesn't show up under the preferences->package settings.

**Comment by kontinuity** [comment]
Cmd+A (Select All) then Ctrl+Alt+Del or Ctrl+Alt+Del+Shift. I had to add the keybindings to my user too

**Comment by dominikwilkowski** [comment]
:+1:

Yeah the shortcuts are not very easy to gasp.

1. You have to select text to process first
2. For `"surplus": true` = `[fn]` + `[shift]` + `[control]` + `[alt]` + `[delete]` 
3. For `"surplus": false` =  `[fn]` + `[control]` + `[alt]` + `[delete]`

_(`[fn]` = If you have no del button on your keyboard)_

**Comment by mkstix6** [comment]
Ye, these shortcuts worked for me on a previous install of the plugin. For some reason they didn't set up automatically the second time I installed it. Do you have the strings I need to enter into the "Key Bindings - User" file handy? Would be a big help.

**Comment by dominikwilkowski** [comment]
sure man:

```
	{
		"command": "delete_blank_lines",
		"args": { "surplus": true },
		"keys": [
			"ctrl+alt+shift+delete"
		]
	},
	{
		"command": "delete_blank_lines",
		"args": { "surplus": false },
		"keys": [
			"ctrl+alt+delete"
		]
	}
```

**Comment by NicholasBuse** [comment]
Closing this issue, but will continue this discussion in #3.
