### ISSUE TITLE
Can't delete surplus blank lines

### ISSUE THREAD

**Issue by leolux** [NicholasBuse/sublime_DeleteBlankLines#7]
The following shotcut does not work on windows:
Ctrl+Alt+Shift+Backspace --> Delete Surplus Blank Lines

Hint: Deleting blank linkes works.

**Comment by leolux** [comment]
Ok, got it now. The reason why it didn't work was because the line inbetween to empty lines had a space (" ") at the beginning of the line.

Maybe the plugin should interpret a line with a space character " " at the beginning as an emtpy line as well. Practically a space character is not a visual character and having only one of it is propably useless.

**Comment by NicholasBuse** [comment]
Resolution of #4 covers this.
