### ISSUE TITLE
Feature Request - Add in a Command Palette or Tools Menu Option

### ISSUE THREAD

**Issue by lunacodes** [NicholasBuse/sublime_DeleteBlankLines#8]
Hey - So I love this plugin, but I can never remember the Commands off the top of my head, and it's really interruptive to go google them or open up the readme file via Sublime.

It would be great if there was Command Palette or Tool Menu (preferably both) entry for these

I'd be willing to work on the feature if you'd like.

**Comment by roman-ku** [comment]
There entire repo is tumbleweed.

**Comment by NicholasBuse** [comment]
Thanks for the Command Palette suggestion. Added.
