### ISSUE TITLE
Deleting surplus lines now adds spaces between each line of code

### ISSUE THREAD

**Issue by stephen147** [NicholasBuse/sublime_DeleteBlankLines#9]
Using Win 10, and shortcut ctrl+alt+shift+backspace now adds carriage returns to each and every line.

I've uninstalled the plugin to ensure that the shortcuts were not mapped to anything else and also checked my keybindings but nothing there to suggest there's anything wrong.

Thanks.

**Comment by NicholasBuse** [comment]
Sorry about that. Should be better now.

**Comment by stephen147** [comment]
Thanks. Automatic update has taken care of it.
